Repository Danielsio/Plan-IT-Web, pull requests merged in 2023-07, with the labels that each got.

#32 Add upComingSession info
  src/pages/GenerateCalendar.jsx
Labels: enhancement

#43 Fix build-docker-image.yml
  .github/workflows/build-docker-image.yml
Labels: invalid

#49 fix redirect uri bug
  src/context/UserContext.jsx
Labels: bug, Approval Required

#59 Refactor ClearStateAndRedirect
  src/App.jsx
  src/context/UserContext.jsx
  src/pages/AddCourse.jsx
  src/pages/AdminCoursesDashboard.jsx
  src/pages/AdminDashboard.jsx
  src/pages/AdminUsersDashboard.jsx
  src/pages/EditCourse.jsx
  src/pages/EditPreferences.jsx
  src/pages/FirstSetupPage.jsx
  src/pages/GenerateCalendar.jsx
  src/pages/Profile.jsx
Labels: Approval Required

#60 Add logic to Re-Generate button
  src/pages/GenerateCalendar.jsx
Labels: enhancement, Approval Required

#65 Refactor FirstSetupPage.jsx
  src/pages/FirstSetupPage.jsx
Labels: Approval Required

#66 Add better UX & UI for CourseItem.jsx in AdminCoursesDashboard.jsx
  src/components/CourseItem.jsx
  src/components/Exam.jsx
  src/components/Footer.jsx
  src/components/FullDayEventItem.jsx
  src/components/Navbar.jsx
  src/components/ProfileCard.jsx
  src/components/UserItem.jsx
  src/context/UserContext.jsx
  src/pages/About.jsx
  src/pages/AddCourse.jsx
  src/pages/AdminCoursesDashboard.jsx
  src/pages/AdminDashboard.jsx
  src/pages/AdminHolidaysDashboard.jsx
  src/pages/AdminUsersDashboard.jsx
  src/pages/EditCourse.jsx
  src/pages/EditPreferences.jsx
  src/pages/FirstSetupPage.jsx
  src/pages/GenerateCalendar.jsx
  src/pages/Home.jsx
  src/pages/Profile.jsx
Labels: enhancement, Approval Required
